export const environment = {
  production: true,
  imagesProfileUrl: 'https://birdpostsqa.blob.core.windows.net/profiles/',
  imagesPostUrl: 'https://birdpostsqa.blob.core.windows.net/posts/',
  userApiUrl: 'https://userapiqa.azurewebsites.net/',
  postApiUrl: 'https://postapiqa.azurewebsites.net/',
  userPostApiUrl: 'https://userpostapiqa.azurewebsites.net/',
  userLabelApiUrl: 'https://userlabelapiqa.azurewebsites.net/',
  birdApiUrl: 'https://birdsapiqa.azurewebsites.net/',
  userInteractionsApi: 'https://userinteractionsapiqa.azurewebsites.net/',
  postInteractionsApi: 'https://postinteractionsapiqa.azurewebsites.net/',
  specieApiUrl: 'https://specieapiqa.azurewebsites.net/',
  googleApiKey: 'AIzaSyAjqE9XcDEwD2SmV9mmf757kYOdwTbJvwQ',
  whiteListDomains:  ['postapiqa.azurewebsites.net', 
                      'userapiqa.azurewebsites.net',
                      'birdsapiqa.azurewebsites.net',
                      'postinteractionsapiqa.azurewebsites.net',
                      'userpostapiqa.azurewebsites.net',
                      'userlabelapiqa.azurewebsites.net',
                      'userinteractionsapiqa.azurewebsites.net',
                      'specieapiqa.azurewebsites.net'],
  blacklistedRoutes: []
}