export const environment = {
  production: true,
  pageDomain:"https://bcsite.azurewebsites.net",
  imagesProfileUrl: 'https://bcommunitystorageaccount.blob.core.windows.net/profiles/',
  imagesPostUrl: 'https://bcommunitystorageaccount.blob.core.windows.net/posts/',
  usersApiUrl: 'https://bcuser.azurewebsites.net/',
  postsApiUrl: 'https://bcposts.azurewebsites.net/',
  searchsApiUrl: 'https://bcsearchs.azurewebsites.net/',
  usersInteractionsApi: 'https://bcuserinteractions.azurewebsites.net/',
  postsInteractionsApi: 'https://bcpostinteractions.azurewebsites.net/',
  externalDataApiUrl: 'https://bcexternaldata.azurewebsites.net/',
  accountApiUrl: 'https://bcaccount.azurewebsites.net/',
  googleApiKey: 'AIzaSyAjqE9XcDEwD2SmV9mmf757kYOdwTbJvwQ',
  whiteListDomains:  ['bcposts.azurewebsites.net', 
                      'bcuser.azurewebsites.net',
                      'bcsearchs.azurewebsites.net',
                      'bcpostinteractions.azurewebsites.net',
                      'bcuser.azurewebsites.net',
                      'bcuserinteractions.azurewebsites.net',
                      'bcexternaldata.azurewebsites.net',
                      'bcaccount.azurewebsites.net'],
  blacklistedRoutes: []
}