export const environment = {
  production: true,
  imagesProfileUrl: 'https://birdpostsqa.blob.core.windows.net/profiles/',
  imagesPostUrl: 'https://birdpostsqa.blob.core.windows.net/posts/',
  userApiUrl: 'https://userapiqa.azurewebsites.net/',
  postApiUrl: 'https://postapiqa.azurewebsites.net/',
  userPostApiUrl: 'https://userpostapiqa.azurewebsites.net/',
  birdApiUrl: 'https://birdsapiqa.azurewebsites.net/',
  voteApiUrl: 'https://votesapi.azurewebsites.net/',
  userLabelApiUrl: 'https://userlabelapi.azurewebsites.net/',
  commentApiUrl: 'https://commentsapi.azurewebsites.net/',
  specieApiUrl: 'https://specieapi.azurewebsites.net/',
  googleApiKey: 'AIzaSyAjqE9XcDEwD2SmV9mmf757kYOdwTbJvwQ',
  whiteListDomains:  ['postapiqa.azurewebsites.net', 
                      'userapiqa.azurewebsites.net',
                      'birdsapiqa.azurewebsites.net',
                      'commentsapi.azurewebsites.net',
                      'userpostapiqa.azurewebsites.net',
                      'votesapi.azurewebsites.net',
                      'userlabelapi.azurewebsites.net',
                      'specieapi.azurewebsites.net'],
  blacklistedRoutes: []
}