export const environment = {
  production: true,
  pageDomain:"https://bcsite.azurewebsites.net",
  imagesProfileUrl: 'https://bcommunitystorageaccount.blob.core.windows.net/profiles/',
  imagesPostUrl: 'https://bcommunitystorageaccount.blob.core.windows.net/posts/',
  userApiUrl: 'https://bcuser.azurewebsites.net/',
  postApiUrl: 'https://bcposts.azurewebsites.net/',
  userLabelApiUrl: 'https://bcuser.azurewebsites.net/',
  birdApiUrl: 'https://bcsearchs.azurewebsites.net/',
  userInteractionsApi: 'https://bcuserinteractions.azurewebsites.net/',
  postInteractionsApi: 'https://bcpostinteractions.azurewebsites.net/',
  specieApiUrl: 'https://bcexternaldata.azurewebsites.net/',
  googleApiKey: 'AIzaSyAjqE9XcDEwD2SmV9mmf757kYOdwTbJvwQ',
  whiteListDomains:  ['bcposts.azurewebsites.net', 
                      'bcuser.azurewebsites.net',
                      'bcsearchs.azurewebsites.net',
                      'bcpostinteractions.azurewebsites.net',
                      'bcuser.azurewebsites.net',
                      'bcuserinteractions.azurewebsites.net',
                      'bcexternaldata.azurewebsites.net'],
  blacklistedRoutes: []
}